# Generated by Django 4.0.2 on 2022-03-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApkInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apk_name', models.CharField(max_length=32, verbose_name='应用名称')),
                ('package_name', models.CharField(max_length=64, verbose_name='包名')),
                ('hash_value', models.CharField(max_length=64, verbose_name='HASH')),
                ('scan_date', models.CharField(max_length=32, verbose_name='扫描日期')),
                ('user_name', models.CharField(max_length=32, verbose_name='用户名')),
            ],
        ),
    ]
