# Generated by Django 4.0.2 on 2022-03-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0003_apkinfo_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apkinfo',
            name='hash_value',
            field=models.CharField(max_length=64, unique=True, verbose_name='HASH'),
        ),
    ]
