# Generated by Django 4.0.2 on 2022-03-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0004_alter_apkinfo_hash_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApkDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apk_name', models.CharField(max_length=32, verbose_name='应用名称')),
                ('version', models.CharField(max_length=32, verbose_name='应用版本')),
                ('version_code', models.CharField(max_length=32, verbose_name='安卓版本代号')),
                ('size', models.CharField(max_length=32, verbose_name='文件大小')),
                ('md5', models.CharField(max_length=64, unique=True, verbose_name='HASH值')),
                ('sha256', models.CharField(max_length=64, verbose_name='sha256')),
                ('max_sdk', models.CharField(max_length=8, verbose_name='最大SDK')),
                ('min_sdk', models.CharField(max_length=8, verbose_name='最小SDK')),
                ('package_name', models.CharField(max_length=64, verbose_name='安装包名称')),
                ('main_activity', models.CharField(max_length=64, verbose_name='主活动')),
                ('app_type', models.CharField(max_length=8, verbose_name='应用类型')),
                ('security_score', models.CharField(max_length=8, verbose_name='安全得分')),
                ('average_cvss', models.CharField(max_length=8, verbose_name='cvss漏洞评分')),
                ('machine_result', models.CharField(max_length=8, verbose_name='机器学习分类结果')),
                ('user_name', models.CharField(max_length=32, verbose_name='用户名')),
            ],
        ),
    ]
