# Generated by Django 4.0.2 on 2022-03-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0005_apkdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApkJson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_value', models.CharField(max_length=64, verbose_name='md5哈希值')),
                ('user_name', models.CharField(max_length=32, verbose_name='用户名')),
                ('data', models.JSONField()),
            ],
        ),
    ]
