# Generated by Django 4.0.2 on 2022-03-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0006_apkjson'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApkLearnResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_value', models.CharField(max_length=64, verbose_name='md5哈希值')),
                ('user_name', models.CharField(max_length=32, verbose_name='用户名')),
                ('knn_result', models.CharField(max_length=8, verbose_name='knn分析结果')),
                ('native_bayes_result', models.CharField(max_length=8, verbose_name='nativeBayes分析结果')),
                ('decision_tree_result', models.CharField(max_length=8, verbose_name='decisionTree分析结果')),
                ('random_forest_result', models.CharField(max_length=8, verbose_name='randomForest分析结果')),
            ],
        ),
    ]
