# Generated by Django 4.0.2 on 2022-03-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0007_apklearnresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineLearnClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_value', models.CharField(max_length=64, verbose_name='md5哈希值')),
                ('user_name', models.CharField(max_length=32, verbose_name='用户名')),
                ('knn_class', models.IntegerField(verbose_name='knn分类结果')),
                ('native_bayes_class', models.IntegerField(verbose_name='native_bayes分类结果')),
                ('decision_tree_class', models.IntegerField(verbose_name='decision_tree分类结果')),
                ('random_forest_class', models.IntegerField(verbose_name='random_forest分类结果')),
            ],
        ),
    ]
