# Generated by Django 4.0.2 on 2022-03-26 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0008_machinelearnclass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MachineLearnClass',
        ),
    ]
